config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  get 'comments/create'

  get 'comments/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  root    'static_pages#home'
  get     'help'      =>  'static_pages#help'
  get     'about'     =>  'static_pages#about'
  get     'contact'   =>  'static_pages#contact'
  get     'terms'     =>  'static_pages#terms'
  get     'privacy'   =>  'static_pages#privacy_policy'

  get     'signup'                   =>  'users#new'
  get     'login'                    =>  'sessions#new'
  post    'login'                    =>  'sessions#create'
  get     '/auth/:provider/callback' =>  'sessions#create'
  get     '/auth/failure'            =>  'sessions#create'
  delete  'logout'                   =>  'sessions#destroy'

  get 'download/:id', to: 'uploads#download', as: :download

  resources :users

  resources :account_activations, only: [:edit, :new, :create]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :uploads,             except: [:index]

  resources :relationships,       only: [:create, :destroy]

  resources :comments,            only: [:create, :destroy]

  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  resources :upload_moderation,   only: [:edit, :update, :destroy, :index]

  resources :search,              only: [:index]

  resources :user_search,         only: [:index]

  resources :charges

  get "uploads"                      => "search#index"

  get 'donate'                       => 'charges#new'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout "no_container", only: :home


  def home
    @uploads = Upload.search do
      with :approved, true
      order_by :weighted_score, :desc
      order_by :created_at, :desc
    end

    @most_popular = @uploads.results.take(24)
    @most_used_tags = Upload.where(approved: true).tag_counts.order(taggings_count: :desc).limit(50)

    @user_search = User.search do
      with :activated, true
      order_by :weighted_score, :desc
      order_by :created_at, :desc
    end

    @users = @user_search.results.take(12)
    @total_results = @user_search.total
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>
<% content_for :description do %>This is the about page for Clipped.io<% end %>

<header>
	<h1>About</h1>
</header>

<h2>What is Clipped?</h2>
<p>
	Clipped is an image sharing community with one clear goal in mind: make it easy to find images with cut out backgrounds.
	Our goal is to be the first (and hopefully last) place you go to find cut out images for your architecture visualizations, collages, and whatever other uses you may have for cut out imagery.  Together we are building the largest database of cutout
	images in the world.  Help us today by uploading some of your cutout photos.
</p>

<h2>Where Can I Use the Images?</h2>
<p>
	All of our images come with a Creative Commons Public Domain CCO licence, meaning they are free of copyrights and can be used
	in nearly any application without any permissions or attribution.  The content within the images may still be protected by trademarks, publicity, or privacy rights, however, so make sure you understand exactly what is legal.  You can read more about it <%= link_to "here", terms_path %>.

	Thanks for visiting!
</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, "Contact") %>

<h1>Contact Clipped</h1>

<p>Please feel free to send questions, comments, feature requests, etc. to <%= link_to "john@creativebasis.com", "mailto: john@creativebasis.com" %>.</p>

app/views/static_pages/help.html.erb
<%= provide(:title, "Help") %>


<h1>Help</h1>
<p>See below for FAQ about Clipped</p>

app/views/static_pages/home.html.erb
<!-- <header class="home">
  <h1>Free Cutout Images</h1>
  <p>The best place to find and share background-free images.</p>
  </header> -->
  <section id="home-banner">
    <div class="container no-pad">
      <h1>Free, High Quality, Cutout Images</h1>
      <div id="home-search">
        <h1 class="cta">What are you looking for?</h1>
        <%= render 'search/upload_search_form' %>
      </div>
    </div>
  </section>

  <section id="home-uploads">
    <div class="container no-pad not-top">
      <h2 class="section-head">Featured</h2>
      <%= link_to "(browse all)", search_index_path(sort_uploads: "weighted_score"), class: "more-link" %>
      <div class="most-popular-uploads">
        <% if @most_popular.any? %>
          <%= render @most_popular %>
        <% end %>
      </div>
    </div>
  </section>

  <section id="home-users">
    <div class="container no-pad not-top">
      <h2 class="section-head">Top Clippers</h2>
      <%= link_to "(browse all)", users_path(sort_users: "weighted_score"), class: "more-link" %>
      <div class="users top-clippers-home">
        <%= render @users %>
      </div>
    </div>
  </section>

  <section id="home-tags">
    <div class="container not-top">
      <h2 class="section-head">Most Popular Tags</h2>
      <div class="tag-items most-popular-home">
        <% @most_used_tags.each do |tag| %>
          <%= render partial: "acts_as_taggable_on/tags/tag", locals: {tag_name: tag.name} %>
        <% end %>
      </div>
    </div>
  </section>

app/views/static_pages/privacy_policy.html.erb
<h1>Privacy Policy</h1>

<p>
We respect and are committed to protecting your privacy. We do not sell or otherwise provide personal information to other companies for the marketing of their own products or services. We will retain your information for as long as your account is active or as needed to provide You services or as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.
</p>
<p>
We reserve the right to disclose your personal information as required by law (e.g., to comply with a subpoena, warrant, or court order) and when we believe that disclosure is necessary to protect our rights, avoid litigation, protect your safety or the safety of others, investigate fraud, and/or respond to a government request. We may also disclose information about You if we determine that such disclosure should be made for reasons of national security, law enforcement, or other issues of public importance.
</p>

app/views/static_pages/terms.html.erb
<h1>Terms of Service</h1>

<p>
The following is a legal agreement between you (You) and the owners and operators of clipped.com (Website), Clipped (We). These Terms of Service (Terms) govern your access to and use of the website, its services (Services) and images (Images). By using the Website You agree to be bound by these Terms. This agreement may be revised or updated without notice.
</p>

<h2>Who can use Clipped</h2>

<p>
You may use the Website only if You can form a binding contract with Clipped, and only in compliance with these Terms and all applicable laws. Any use or access by anyone under the age of 13 is prohibited.
</p>


<h2>Downloading and use of Images</h2>

<p>CC0 Via download provided Images on Clipped are bound to Creative Commons Deed CC0. To the extent possible under law, uploaders of Clipped have waived all copyright and related or neighboring rights to these Images. You are free to adapt and use the Images for commercial purposes without attributing the original author or source. Although absolutely not required, a link back to Clipped would be nice.</p>

<h2>Limitations</h2>

<p>
Images depicting identifiable persons may not be used for pornographic, unlawful or other immoral purposes, or in a way that can give a bad name to people, or to imply endorsement of products and services by those persons, brands, organisations, etc.
Since Clipped does not require a written Model Release for each Image that has identifiable people on it, We cannot guarantee that You will be able to use the Image for any purpose You like. Also, if there is a model release for the Image, We do not represent or make warranties whatsoever as to the legality or validity of it.
Furthermore, certain Images may be subject to additional copyrights, property rights, trademarks etc. and may require the consent of a third party or the license of these rights. Clipped does not represent or make any warranties that it owns or licenses any of the mentioned, nor does it grant them. It's your and the Image uploader's responsibility to make sure that all the necessary rights, consents and licenses for the use of the Images are provided.
You are not allowed to mass download Images with an application, or reuse a big part of the Images for redistribution on a similar Website. Texts including image descriptions and tags are copyrighted.
Clipped cannot be held responsible for any copyright violations, and cannot guarantee the legality of the Images stored in its system. If You want to make sure, always contact the photographers. You use the site and the photos at your own risk!
</p>

<h2>Uploading Images</h2>

<p>
You may upload photographs or graphics to the Website, and Clipped will screen these uploads to see if they are suitable for distribution. Clipped does not accept any adult oriented images.
</p>
<p>
By uploading, You release Images under Creative Commons Deed CC0 into the public domain. This applies worldwide. In case this is not legally possible, You grant anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.
</p>
<p>
You are solely responsible for the Images You upload. You warrant that You own all proprietary rights regarding the Image, and You are obliged to obtain a non-exclusive, perpetual, irrevocable, worldwide, and royalty-free Model and/or Property Release and/or any other permission necessary concerning the use of this work for any purpose, without any conditions, unless such conditions are required by law.
</p>
<p>
Furthermore, You acknowledge that Clipped does not allow the upload of Images that infringe on any copyright, property right, trademark or any other applicable right.
</p>
<p>
You accept that even though We do our best to prevent it from happening, Clipped cannot be held responsible for the misuse or abuse of any Image.
</p>
<p>
We also reserve the right to remove any approved Image at any time if We believe it's defective, of poor quality or infringe on any right.
</p>

<h2>Indemnification for Breach of Terms</h2>

<p>
You agree to indemnify and hold harmless Clipped from and against any and all loss, expenses, damages, and costs, including without limitation reasonable attorneys fees, resulting, whether directly or indirectly, from your violation of the Terms. You also agree to indemnify and hold harmless Clipped from and against any and all claims brought by third parties arising out of your use of the Website.
</p>

<h2>Warranty and Liability</h2>

<p>
THE WEBSITE AND THE IMAGES ARE PROVIDED "AS IS". WE OFFER NO WARRANTY, EXPLICIT OR IMPLIED, REGARDING ANY IMAGES, THE WEBSITE, THE ACCURACY OF ANY INFORMATION, OR ANY RIGHTS OR LICENSES UNDER THIS AGREEMENT INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Clipped DOES NOT REPRESENT OR WARRANT THAT THE WEBSITE OR THE IMAGES WILL MEET YOUR REQUIREMENTS OR THAT THEIR USE WILL BE UNINTERRUPTED OR ERROR FREE.
</p>

<p>
Clipped SHALL NOT BE LIABLE TO YOU OR TO ANY OTHER PERSON OR ENTITY FOR ANY GENERAL, PUNITIVE, SPECIAL, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES, OR LOST PROFITS OR ANY OTHER DAMAGES, COSTS OR LOSSES ARISING OUT OF YOUR USE OF THE WEBSITE OR THE IMAGES.</p>