config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  get 'comments/create'

  get 'comments/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  root    'static_pages#home'
  get     'help'      =>  'static_pages#help'
  get     'about'     =>  'static_pages#about'
  get     'contact'   =>  'static_pages#contact'
  get     'terms'     =>  'static_pages#terms'
  get     'privacy'   =>  'static_pages#privacy_policy'

  get     'signup'                   =>  'users#new'
  get     'login'                    =>  'sessions#new'
  post    'login'                    =>  'sessions#create'
  get     '/auth/:provider/callback' =>  'sessions#create'
  get     '/auth/failure'            =>  'sessions#create'
  delete  'logout'                   =>  'sessions#destroy'

  get 'download/:id', to: 'uploads#download', as: :download

  resources :users

  resources :account_activations, only: [:edit, :new, :create]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :uploads,             except: [:index]

  resources :relationships,       only: [:create, :destroy]

  resources :comments,            only: [:create, :destroy]

  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  resources :upload_moderation,   only: [:edit, :update, :destroy, :index]

  resources :search,              only: [:index]

  resources :user_search,         only: [:index]

  resources :charges

  get "uploads"                      => "search#index"

  get 'donate'                       => 'charges#new'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :uploads, dependent: :destroy

  has_many :favoriter_relationships,
            class_name:  "Relationship",
            foreign_key: "favoriter_id",
            dependent:   :destroy

  has_many :favoriting,
            through: :favoriter_relationships,
            source: :favorited

  has_many :comments,
            foreign_key: "commenter_id",
            dependent: :destroy

  has_many :commentees,
            through: :comments

  attr_accessor :remember_token, :activation_token, :reset_token, :avatar_original_width
  before_save   :downcase_email
  before_create :create_activation_digest

  searchable do
    text :name
    text :username
    text :email
    boolean :activated
    double :weighted_score
    time :created_at
  end
  handle_asynchronously :solr_index

  DEFAULT_AVATAR_URL = "https://s3-us-west-2.amazonaws.com/entourageappdev/users/avatars/default/profile.png"
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :username, presence: true, :length => { :in => 3..20 }, uniqueness: {case_sensitive: false}, format: { with: /\A\w*\z/, :message => 'only letters, numbers, and underscores allowed' }
  validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  validates :name, length: {maximum: 50}
  #allow blank allows for profile update without changing password, password presence is ensured by 'has_secure_password' when signing up
  validates :password, length: {minimum: 8}, allow_blank: true

  has_secure_password

  has_attached_file :avatar, 
                    styles: { profile: { geometry: '300x300#', processors: [:cropper] }, large: '500x500>' },
                    :default_url => DEFAULT_AVATAR_URL,
                    :default_style => :profile,
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
                   :s3_protocol => 'https',
                    :s3_host_name => "s3-us-west-2.amazonaws.com",
                    :bucket => ENV['AWS_BUCKET']

  after_post_process :save_image_dimensions

  validates_attachment  :avatar,
                        :size => { :less_than => 50.megabytes },
                        :content_type => { :content_type => /\Aimage/ }

  def s3_credentials
    { :bucket => ENV['AWS_BUCKET'], 
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'], 
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'] }
  end

  def to_param
    username
  end

  def avatar_from_url(url)
    if url
      avatar_url = URI.parse(url)
      #fix for Google bringing in small image
      if avatar_url.query == "sz=50"
        avatar_url.query = "sz=300"
      end

      if !avatar_url.scheme
        avatar_url.scheme = 'https'
      end
      avatar_url = avatar_url.to_s
      self.avatar = URI.parse(avatar_url)
    else
      avatar_from_url(DEFAULT_AVATAR_URL)
    end
  end

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end

    def sort_options
      { Newest: "created_at", Popularity: "weighted_score" }
    end

  end

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def avatar_geometry(style = :original)
    @geometry ||= {}
    avatar_path = (avatar.options[:storage] == :s3) ? avatar.url(style) : avatar.path(style)
    uri = URI(avatar_path)
    request = Net::HTTP.new uri.host
    response = request.request_head uri.path
    a = response.code.to_i
    if (response.code.to_i == 200)
      @geometry[style] ||= Paperclip::Geometry.from_file(avatar_path)
    else
      self.avatar_from_url()
      self.avatar_geometry(style)
    end
  end

  def ratio
    self.avatar_geometry(:original).width / self.avatar_geometry(:large).width
  end

  # Activates an account.
  def activate(token)
    if !self || self.activated? || !self.authenticated?(:activation, token)
      return false
    end

    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # Creates password reset digest
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Sends password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Likes an upload.
  def favorite(upload)
    favoriter_relationships.create(favorited_id: upload.id)
  end

  def unfavorite(upload)
    favoriter_relationships.find_by(favorited_id: upload.id).destroy
  end

  def favoriting?(upload)
    favoriting.include?(upload)
  end

  def downloads_per_view
    self.uploads.sum(:downloads / :view)
  end

  def update_stats
    self.favorites_count = self.uploads.where(approved: true).sum(:favorites_count)
    self.downloads_count = self.uploads.where(approved: true).sum(:downloads)
    self.save!
    Sunspot.delay.index self
  end
  handle_asynchronously :update_stats

  def weighted_score
    m = ModelStatistics.new(self)
    m.composite_score_users
  end

  def upload_owner?(upload)
    if upload
      self.uploads.exists?(upload.id)
    end
  end

  # Approve an upload
  def approve(upload)
    upload.approved = true
    upload.save!
  end

  # Disapprove an upload
  def disapprove(upload)
    upload.approved = false
    upload.save!
  end

  def approved_uploads_count
    self.uploads.where(approved: true).count
  end

    #creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token   =  User.new_token
    self.activation_digest  =  User.digest(activation_token)
  end

  def reprocess_avatar
    avatar.reprocess!
  end

  def commenting_on?(upload)
    commentees.include?(upload)
  end

  def comment_on(upload:, body:)
    comments.build(commentee_id: upload.id) do |comment|
      comment.body = body
    end
  end

  private
    #converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    def save_image_dimensions
      tempfile = avatar.queued_for_write[:original]
      unless tempfile.nil?
        geometry = Paperclip::Geometry.from_file(tempfile)
        self.avatar_original_width = geometry.width.to_i
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "no_container", only: :show
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def index
    @user_search = User.search do
      with :activated, true
      if params[:user_search].present?
        fulltext params[:user_search] do
          minimum_match 1
        end
      end
      order_by params[:sort_users], :desc if params[:sort_users].present?
      order_by :created_at, :desc
      paginate page: params[:page], per_page: 30
    end

    @users = @user_search.results
    @total_results = @user_search.total
    # create a deep clone of params for manipulation in view
    @user_query = Marshal.load(Marshal.dump(params))

    respond_to do |format|
      format.html { render 'users/index' }
      format.js
    end
  end

  def show
    @uploads = UploadPolicy::Scope.new(current_user, @user.uploads).resolve.paginate(page: params[:page])
    authorize @user

    if params[:filter_uploads] == "unapproved"
      @uploads = @uploads.where(approved: false)
    elsif params[:filter_uploads] == "favorites"
      @uploads = @user.favoriting.paginate(page: params[:page])
    else
      @uploads = @uploads.where(approved: true)
    end

    if params[:filter_uploads] && !params[:page]
      render "filter.js.erb"
    else
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.delay.avatar_from_url(User::DEFAULT_AVATAR_URL)
      @user.send_activation_email
      flash[:notice] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    respond_to do |format|
      if @user.update_attributes(user_params)
        if params[:user][:crop_h]
          @user.reprocess_avatar
        end
        format.js {}
        format.html {
          if params[:user][:crop_h]
            flash[:success] = "Profile image successfully updated"
            redirect_to(request.referrer || @user)
          else
            flash[:success] = "Profile successfully updated"
            redirect_to @user
          end
        }
      else
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    authorize @user
    log_out if logged_in?
    @user.destroy
    flash[:success] = "User deleted successfully"
    redirect_to root_url
  end

  private

    def user_params
      params.require(:user).permit(:username, :name, :email, :password, :password_confirmation, :avatar, :crop_x, :crop_y, :crop_w, :crop_h, :avatar_original_width)
    end

    def set_user
      @user = User.find_by_username(params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper

   # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_crop.html.erb
<div id="edit-user-avatar" class="modal">
  <label for="modal-edit-avatar">
    <div class="modal-trigger">
      <%= image_tag @user.avatar.url(:profile), id: "profile-avatar", class: "avatar" %>
      <div class="hover-overlay">
        <i class="fa fa-camera"></i>
      </div>
    </div>
  </label>
  <input class="modal-state" id="modal-edit-avatar" type="checkbox" />
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <div class="modal-saving overlay">
        <p>saving image</p>
      </div>
      <div class="modal-close" for="modal-edit-avatar"></div>
      <h2>Edit Profile Picture</h2>
      <div class="modal-left">
        <div id="avatar-preview-container" class="avatar">
          <%= image_tag @user.avatar.url(:original), id: "avatar-preview" %>
        </div>
        <div id="file-upload">
          <span>Upload new image</span>
          <%= a.file_field :avatar, id: "avatar-upload" %>
        </div>
        <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
          <%= a.hidden_field attribute, :id => attribute %>
        <% end %>
        <%= a.submit "Save", id: "submit-crop" %>
      </div>
      <div class="modal-right">
        <%= image_tag @user.avatar.url(:original), :id => "cropbox",
          data: {
            width: @user.avatar_original_width,
            crop_x: @user.crop_x,
            crop_y: @user.crop_y,
            crop_w: @user.crop_w,
            crop_h: @user.crop_h,
            image_url: @user.avatar.url(:original)
          } %>
      </div>
    </div>
  </div>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :email %>
<%= f.email_field :email%>

<%= f.label :name %>
<%= f.text_field :name%>

<%= f.label :password %>
<%= f.password_field :password%>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation%>

app/views/users/_upload.html.erb
<% present(upload) do |upload| %>
  <%= content_tag :div, class: "upload #{upload.tagged_class}", data: {id: upload.id} do %>
    <%= link_to upload, class: "upload-thumb", id: "upload-#{upload.id}" do %>
      <%= image_tag upload.src(:thumb), class: "#{upload.processed_class}" %>
    <% end %>
    <% if policy(:upload_moderation).update? %>
      <div id="approve-link" class="icon-link">
        <%= render 'upload_moderation/moderation_form', upload: upload %>
      </div>
    <% end %>
    <% if policy(upload).update? %>
      <%= upload.current_tags %>
      <%= render "acts_as_taggable_on/tags/update_form", upload: upload%>
    <% end %>
    <% if policy(:upload_moderation).update? %>
      <%= form_for upload, method: :patch, html: { class: "details", id: "update-details-form" }, remote: true do |f| %>
        <%= render partial: 'uploads/perspective_form', locals: {f: f, upload: upload} %>
        <%= render partial: 'uploads/category_form', locals: {f: f, upload: upload} %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_upload_tabs.html.erb
<div id="user-sort-tabs" class="tabs">
  <%= link_to "Uploads (#{@user.approved_uploads_count})", { controller: "users", action: "show", id: @user, filter_uploads: "approved" }, remote: true, class: "active" %>
  <% if policy(@user).update? %>
    <%= link_to "Awaiting Approval (#{@user.uploads.where(approved: false).count})", { controller: "users", action: "show", id: @user, filter_uploads: "unapproved" }, remote: true %>
    <%= link_to "Favorites (#{@user.favoriting.count})", { controller: "users", action: "show", id: @user, filter_uploads: "favorites" }, remote: true  %>
  <% end %>
</div>

app/views/users/_user.html.erb
<%= link_to user, class: "user-thumb" do %>
  <div class="card">
    <%= image_tag user.avatar.url(:profile), class: "avatar" %>
    <p class="user-thumb-name">@<%= user.username %></p>

    <div class="hover-overlay">
      <ul class="user-thumb-stats">
        <li><span class="stats-label"><i class="fa fa-upload"></i></span><span class="stats-val"><%= user.approved_uploads_count %></span></li>
        <li><span class="stats-label"><i class="fa fa-star"></i></span><span class="stats-val"><%= user.favorites_count %></span></li>
        <li><span class="stats-label"><i class="fa fa-download"></i></span><span class="stats-val"><%= user.downloads_count%></span></li>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_user_info.html.erb
<div class="user-info">
  <% if policy(@user).update? %>
    <%= form_for @user, html: {class: "signup-form", id: "edit-user-form"} do |a| %>
      <%= render 'crop', a: a %>
    <% end %>
  <% else %>
    <%= image_tag @user.avatar.url(:profile), id: "profile-avatar", class: "avatar" %>
  <% end %>
  <h1 class="user-name"><%= @user.name %></h3>
  <p class="username">@<%= @user.username %></h3>
  <% if policy(@user).update? %>
    <%= link_to "Edit Profile", edit_user_path(@user), class: "edit-link" %>
  <% end %>
  <p id="user-created-date">Joined: <%= @user.created_at.strftime("%B %Y") %></p>
</div>

app/views/users/_user_stats.html.erb
<div class="user-stats stats">
  <ul>
    <li><%= @user.approved_uploads_count %><span>Uploads</span></li>
    <li><%= @user.downloads_count %><span>Downloaded</span></li>
    <li><%= @user.favorites_count %><span>Favorited</span></li>
  </ul>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit profile') %>

<div class="gateway-form">

  <h1>Update Your Profile</h1>

  <div class="edit_form">

    <%= form_for @user, html: {class: "signup-form", id: "edit-user-form"} do |a| %>
      <%= render 'crop', a: a %>
    <% end %>

    <%= form_for @user, html: {class: "signup-form", id: "edit-user-form"} do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save Changes" %>
    <% end %>

    <%= link_to "delete account", @user, method: :delete, data: { confirm: "delete your account?" }, id: "delete-user" %>

  </div>
</div>

app/views/users/filter.js.erb
$(".user-uploads").html("<%= j render partial: "upload", collection: @uploads %>");
setTagsEditors();
$("#infinite-scrolling").html("<%= j will_paginate @uploads %>");
<% if @uploads.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @uploads %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>All Clippers</h1>

<div id="user-sort-tabs" class="tabs">
  <% if @user_query[:sort_users] == "created_at" %>
    <%= link_to "Top Clippers", users_path(sort_users: "weighted_score") %>
    <%= link_to "Newest Clippers", users_path(sort_users: "created_at"), class: "active" %>
  <% else %>
    <%= link_to "Top Clippers", users_path(sort_users: "weighted_score"), class: "active" %>
    <%= link_to "Newest Clippers", users_path(sort_users: "created_at") %>
  <% end %>
</div>

<div id="users-index-container" class="users">
  <%= render @users %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate @users%>
</div>

app/views/users/index.js.erb
$('#users-index-container').append('<%= j render @users %>');
<% if @users.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @users %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<section class="gateway-form">
	<%= render "new_form" %>
</section>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<section class="user_profile">
  <%= render "user_info" %>
  <%= render "user_stats" %>
  <% if current_user?(@user) %>
    <%= link_to new_upload_path do %>
      <button class="upload-btn">Upload</button>
    <% end %>
  <% end %>
</section>
<section class="uploads-index">
  <div class="container">
    <%= render "upload_tabs" %>
    <div class="user-uploads">
      <% if @user.uploads.any? %>
        <%= render partial: "upload", collection: @uploads %>
      <% end %>
    </div>
  </div>
</section>
<div id="infinite-scrolling">
  <%= will_paginate @uploads %>
</div>

app/views/users/show.js.erb
$('.user-uploads').append('<%= j render partial: "upload", collection: @uploads %>');
setTagsEditors();
<% if @uploads.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @uploads %>');
<% else %>
  $('.pagination').remove();
<% end %>