config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  get 'comments/create'

  get 'comments/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  root    'static_pages#home'
  get     'help'      =>  'static_pages#help'
  get     'about'     =>  'static_pages#about'
  get     'contact'   =>  'static_pages#contact'
  get     'terms'     =>  'static_pages#terms'
  get     'privacy'   =>  'static_pages#privacy_policy'

  get     'signup'                   =>  'users#new'
  get     'login'                    =>  'sessions#new'
  post    'login'                    =>  'sessions#create'
  get     '/auth/:provider/callback' =>  'sessions#create'
  get     '/auth/failure'            =>  'sessions#create'
  delete  'logout'                   =>  'sessions#destroy'

  get 'download/:id', to: 'uploads#download', as: :download

  resources :users

  resources :account_activations, only: [:edit, :new, :create]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :uploads,             except: [:index]

  resources :relationships,       only: [:create, :destroy]

  resources :comments,            only: [:create, :destroy]

  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  resources :upload_moderation,   only: [:edit, :update, :destroy, :index]

  resources :search,              only: [:index]

  resources :user_search,         only: [:index]

  resources :charges

  get "uploads"                      => "search#index"

  get 'donate'                       => 'charges#new'

end

app/models/upload.rb
class Upload < ActiveRecord::Base

  belongs_to :user

  has_many :favorited_relationships,
            class_name:  "Relationship",
            foreign_key: "favorited_id",
            dependent:   :destroy

  has_many :favoriters,
            through: :favorited_relationships

  has_many :comments,
            foreign_key: "commentee_id",
            dependent: :destroy

  has_many :commenters,
            through: :comments

  default_scope -> { order(created_at: :desc) }
  acts_as_ordered_taggable

  searchable do
    text :tag_list, stored: true
    text :perspective, stored: true
    text :category, stored: true
    boolean :approved, stored: true
    integer :perspective_id, stored: true
    integer :category_id, stored: true
    string :tag_list, multiple: true, stored: true
    double :weighted_score, stored: true
    time :created_at, stored: true
  end
  handle_asynchronously :solr_index
  # handle_asynchronously :remove_from_index

  validates :user_id, presence: true

  enum perspective: [ :not_applicable, :front, :side_front, :side, :side_back, :back, :above, :below ]
  enum category: [:uncategorized, :people, :animals, :plants, :vehicles, :objects]

  # Store an unescaped version of the escaped URL that Amazon returns from direct upload.
  def direct_upload_url=(escaped_url)
    write_attribute(:direct_upload_url, (CGI.unescape(escaped_url) rescue nil))
  end

  has_attached_file :image, 
                    styles: { original: "4000x4000>", large: "1500x1500>", medium: "750x750>", thumb: "x300>" },
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
                    :s3_protocol => 'https',
                    :s3_host_name => "s3-us-west-2.amazonaws.com",
                    :bucket => ENV['AWS_BUCKET']

  validates_attachment  :image,
                        :file_name => { :matches => /\.(gif|jpg|jpeg|tiff|png)$/i },
                        :size => { :less_than => 50.megabytes },
                        :presence => true

  def s3_credentials
    { :bucket => ENV['AWS_BUCKET'], 
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'], 
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'] }
  end

  def perspective_id
    Upload.perspectives[self.perspective]
  end

  def category_id
    Upload.categories[self.category]
  end

  def download_url
    s3 = AWS::S3.new
    bucket = s3.buckets[image.bucket_name]
    object = bucket.objects[image.s3_object(:original).key]
    object.url_for(:get,
      expires: 10.minutes,
      response_content_disposition: 'attachment'
    ).to_s
  end

  def weighted_score
    stats = ModelStatistics.new(self)
    stats.composite_score_uploads
  end

  def commented_on_by?(user)
    commenters.include?(user)
  end

  class << self

    def sorted_by(attribute)
      Upload.all.reorder("#{attribute} DESC")
    end

    # def sorted_by_weighted_score
    #   Upload.all.sort_by(&:weighted_score).reverse!
    # end

    def perspective_collection(perspectives = [])
      Upload.where(perspective: perspectives)
    end

    def perspective_array
      a = Upload.perspectives.map do |k,v|
        [k.humanize, k]
      end
      return a
    end

    def category_array
      a = Upload.categories.map do |k,v|
        [k.humanize, k]
      end
      return a
    end

    def sort_options
      {Relevance: "", Newest: "created_at", Popularity: "weighted_score"}
    end

    # def perspective_choices
    #   byebug
    #   Upload.perspectives.except!(:not_applicable)
    # end

    def category_collection(categories = [])
      Upload.where(category: categories)
    end

    def perspective_id_name(int)
      name = Upload.perspectives.map do |key, value|
        key.humanize
      end
      return name[int]
    end

    def category_id_name(int)
      name = Upload.categories.map do |key, value|
        key.humanize
      end
      return name[int]
    end

    # def category_choices
    #   Upload.categories.except!(:uncategorized)
    # end

  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  def new
    @upload = current_user.uploads.new
    render layout: "dropzone_uploader"
  end

  def create
    @upload = current_user.uploads.new(upload_params)
    authorize @upload
    SaveImage.call(upload: @upload)
    if @upload.save
      @upload.user.update_stats
      UploadModerationMailer.new_upload_email(@upload).deliver_later
      flash[:notice] = "Please allow for a day or two before your uploads are approved."
      render json: @upload
      ProcessUploads.call(upload: @upload)
    else
      render json: { error: @upload.errors.full_messages.join(',')}, :status => 400
    end
  end

  def update
    @upload = Upload.find(params[:id])
    authorize @upload
    respond_to do |format|
      if @upload.update(upload_params)
        format.js
        format.json { render json: @upload }
      else
        flash.now[:error] = "There was an issue updating your upload"
        format.html { render "show" }
      end
    end
  end

  def show
    @upload = Upload.find(params[:id])
    @upload.views += 1
    @upload.save
    authorize @upload
    @comments = @upload.comments.hash_tree
  end

  def destroy
    @upload = Upload.find(params[:id])
    authorize @upload
    @upload.destroy
    @upload.user.update_stats
    respond_to do |format|
      format.html {
        flash[:success] = "Image successfully deleted"
        redirect_to current_user
      }
      format.js
    end
  end

  def download
     @upload = Upload.find(params[:id])
     @upload.downloads += 1
     @upload.save!
     @upload.user.update_stats
     redirect_to @upload.download_url
  end

  private

    def upload_params
      params.require(:upload).permit(:image, :direct_upload_url, :tag_list, :perspective, :category, :dz_thumb)
    end

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || login_path)
    end
end

app/helpers/uploads_helper.rb
module UploadsHelper

end

app/views/uploads/_clipper_card.html.erb
<div class="upload-clipper card">
  <h2 class="title">Clipper</h2>
  <div class="media-object">
    <%= link_to user_path(upload.user), class: "media-figure" do %>
      <%= image_tag upload.clipper_avatar, class: "avatar" %>
    <% end %>
    <div id="upload-clipper-info media-body">
      <p class="clipper-name"><%= link_to "@#{upload.user.username}", user_path(upload.user) %></p>
      <p class="clipper-upload-count"><%= pluralize(upload.user.approved_uploads_count, "upload") %></p>
    </div>
  </div>
</div>

app/views/uploads/_details_card.html.erb
<div class="upload-details card">
  <h2 class="title">Details</h2>
  <%= form_for @upload, method: :patch, html: { class: "details", id: "update-details-form" }, remote: true do |f| %>
    <table id="upload-show-details-table">
      <tbody>
        <tr>
          <td>Perspective:</td>
          <td class="detail-val"><%= link_to upload.perspective.humanize, search_index_path(perspective_id: Upload.perspectives[upload.perspective], perspective: upload.perspective), id: "selected-perspective", class: "attr-link" %><%= render partial: 'perspective_form', locals: {f: f} %>
        </td>
        </tr>
        <tr>
          <td>Category:</td>
          <td class="detail-val"><%= link_to upload.category.humanize, search_index_path(category_id: Upload.categories[upload.category], category: upload.category), id: "selected-category", class: "attr-link" %><%= render partial: 'category_form', locals: {f: f } %></td>
        </tr>
        <tr>
          <td>Views:</td>
          <td class="detail-val"><%= upload.views %></td>
        </tr>
        <tr>
          <td>Downloads:</td>
          <td class="detail-val"><%= upload.downloads %></td>
        </tr>
        <tr>
          <td>Favorited:</td>
          <td class="detail-val" id="favorites_count"><%= upload.favorites_count %></td>
        </tr>
        <tr>
          <td>Uploaded:</td>
          <td class="detail-val"><%= time_ago_in_words(upload.created_at) %> ago</td>
        </tr>
      </tbody>
    </table>
    <% if policy(upload).update? %>
      <%= f.submit "Update", id: "update-details-btn", class: "hidden btn update-upload-btn" %>
      <%= link_to 'Edit', edit_upload_path(upload), class: "js-link", id: "edit-category-link", remote: true %>
    <% end %>
  <% end %>
  <div id="upload-download">
    <%= render partial: "download", locals: {upload: @upload} %>
  </div>
</div>

app/views/uploads/_download.html.erb
<%= link_to download_path(upload) do %>
	<button>Download</button>
<% end %>

app/views/uploads/_dropzone.html.erb
<div id="fullscreen-overlay" class="hidden overlay">
  <p>Saving Images...</p>
</div>

<%= s3_uploader_form callback_url: uploads_url, id: "s3-uploader", class: "dropzone", 
  callback_param: "upload[direct_upload_url]", 
  expiration: 24.hours.from_now.utc.iso8601, 
  max_file_size: 50.megabytes, 
  key: "uploads/#{Time.now.strftime("%y%m%d")}/#{SecureRandom.hex}/${filename}" do %>

  <%= hidden_field_tag  "Content-type", "" %>
  <div class="fallback">
    <%= file_field_tag 'file', multiple: true %>
  </div>

  <%= content_tag "div", id: "uploader-container", class: "flex-container", data: { userid: current_user.username } do %>
    <div id="uploader-controls" class="card" style="display: none;">
      <button type="button" id="save-uploads" name="x-ignore-save" disabled>save</button>
      <button type="button" id="remove-all-uploads" name="x-ignore-remove-all" class="secondary">remove all</button>
    </div>

    <div id="dropzone-upload-text">
      <div class="dz-message"><h1>Drag files here or</h1></div>
      <div id="clickable">
        <button name="x-ignore-button">Click here to select files</button>
      </div>
    </div>
    <div id="upload-previews" class="flex-container"></div>
  <% end %>

  <div id="preview-template" class="dropzone-previews" style="display: none;">
    <div class="dz-preview dz-file-preview card">
      <div class="overlay hidden">
        <p>saving...</p>
      </div>
      <div class="dz-image-container">
        <div class="dz-success-mark animated fadeInDown"><i class="fa fa-check-circle-o fa-3x"></i></div>
        <div class="dz-error-mark animated shake"><i class="fa fa-exclamation-circle fa-3x"></i></div>
        <img data-dz-thumbnail />
      </div>

      <div class="dz-details">
        <div class="dz-progress fadeOut"><span class="dz-upload" data-dz-uploadprogress></span></div>
        <!-- <div class="dz-filename"><span data-dz-name></span></div>-->	
        <div class="dz-size" data-dz-size></div>
      </div>
      <div id="dropzone-upload-tags" class="hidden">
        <div class="tags-container"></div>
        <%= render partial: "acts_as_taggable_on/tags/update_form" %>
      </div>

      <div class="dz-error-message"><span data-dz-errormessage></span></div>
    </div>
  </div>

<% end %>

app/views/uploads/_gender_form.html.erb
<%= f.select :gender, options_for_select(Upload.gender_array, @upload.gender), {}, {class: "hidden edit-upload-form"} %>

app/views/uploads/_image.html.erb
<%= content_tag :div, class: "upload-single-image card gray #{upload.approval_class}" do %>
  <%= image_tag upload.src(:large) %>
<% end %>

app/views/uploads/_perspective_form.html.erb
<% upload ||= @upload %>
<%= f.select :perspective, options_for_select(Upload.perspective_array, upload.perspective), {}, {class: "hidden edit-upload-form"} %>

app/views/uploads/_tags_card.html.erb
<div class="upload-tags card" data-id=<%= upload.id %>>
  <h2 class="title">Tags</h2>
  <div class="tags-container">
    <%= render upload.tags %>
  </div>
  <% if policy(upload).update? %>
    <%= render 'acts_as_taggable_on/tags/update_form' %>
  <% end %>
</div>

app/views/uploads/_upload.html.erb
<% present(upload) do |upload| %>
  <%= content_tag :div, class: "upload", data: {id: upload.id} do %>
    <%= link_to upload, class: "upload-thumb", id: "upload-#{upload.id}" do %>
      <%= image_tag upload.src(:thumb), class: "#{upload.processed_class}" %>
    <% end %>
  <% end %>
<% end %>

app/views/uploads/create.js.erb
<% if @upload.persisted? %>
  $('#upload_<%=params[:unique_id]%>').hide();
<% else %>
  $('#upload_<%=params[:unique_id]%> div.progress').removeClass('active progress-striped').addClass('progress-danger');
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing Entourage Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/new.html.erb
<%= render 'dropzone' %>

app/views/uploads/show.html.erb
<% present(@upload) do |upload| %>

  <div class="upload-single-left-content">
    <%= render partial: "image", locals: {upload: upload} %>
    <%= render partial: "interactions", locals: {upload: upload} %>
    <%= render partial: "comments/comments", locals: {upload: upload} %>
  </div>

  <div class="upload-info">
    <%= render partial: "clipper_card", locals: {upload: upload} %>
    <%= render partial: "tags_card", locals: {upload: upload} %>
    <%= render partial: "details_card", locals: {upload: upload} %>
  </div>

<% end %>

app/views/uploads/update.js.erb
if ($(.uploads.show).length) {
  $(".tags-form").addClass("hidden");
  $(".js-link").removeClass("hidden");
  $(".tags-list").removeClass("update");
  $(".update-upload-btn").addClass("hidden");

  $('.tag-items').html("<%= j (render @upload.tags) %>");
  $(".edit-upload-form").addClass("hidden");
  $('.attr-link').removeClass('hidden');
  $('#selected-perspective').html("<%= j (link_to @upload.perspective.humanize, uploads_path(perspective: Upload.perspectives[@upload.perspective]), class: 'perspective') %>");
  $('#selected-category').html("<%= j (link_to @upload.category.humanize, uploads_path(category: Upload.categories[@upload.category]), class: 'category') %>");
} else if ($(".upload_moderation.index").length){

}