config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  get 'comments/create'

  get 'comments/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  root    'static_pages#home'
  get     'help'      =>  'static_pages#help'
  get     'about'     =>  'static_pages#about'
  get     'contact'   =>  'static_pages#contact'
  get     'terms'     =>  'static_pages#terms'
  get     'privacy'   =>  'static_pages#privacy_policy'

  get     'signup'                   =>  'users#new'
  get     'login'                    =>  'sessions#new'
  post    'login'                    =>  'sessions#create'
  get     '/auth/:provider/callback' =>  'sessions#create'
  get     '/auth/failure'            =>  'sessions#create'
  delete  'logout'                   =>  'sessions#destroy'

  get 'download/:id', to: 'uploads#download', as: :download

  resources :users

  resources :account_activations, only: [:edit, :new, :create]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :uploads,             except: [:index]

  resources :relationships,       only: [:create, :destroy]

  resources :comments,            only: [:create, :destroy]

  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  resources :upload_moderation,   only: [:edit, :update, :destroy, :index]

  resources :search,              only: [:index]

  resources :user_search,         only: [:index]

  resources :charges

  get "uploads"                      => "search#index"

  get 'donate'                       => 'charges#new'

end

app/views/refills/_navigation.html.erb
<header class="navigation">
  <div class="menu-wrapper">
    <%= link_to(image_tag("https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png", :alt => "logo", :title => "Home"), root_path, :class=>"logo") %>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link"><%= link_to "Home",   root_path %></li>
        <li class="nav-link"><%= link_to "About",   about_path %></li>
        <li class="nav-link"><%= link_to "Help",   help_path %></li>
        <li class="nav-link more"><a href="javascript:void(0)">More</a>
          <ul class="submenu">
            <li><a href="javascript:void(0)">Submenu Item</a></li>
            <li><%= link_to "Help",   help_path %></li>
          </ul>
        </li>
        
      </ul>
    </div>
    <div class="navigation-tools">
      <div class="search-bar">
        <div class="search-and-submit">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon.png" alt="">
          </button>
        </div>
      </div>
      <a href="javascript:void(0)" class="sign-up">Sign Up</a>
    </div>
  </div>
</header>

<script>
  $(function() {
    var menu = $('#navigation-menu');
    var menuToggle = $('#js-mobile-menu');
    var signUp = $('.sign-up');

    $(menuToggle).on('click', function(e) {
      e.preventDefault();
      menu.slideToggle(function(){
        if(menu.is(':hidden')) {
          menu.removeAttr('style');
        }
      });
    });

    // underline under the active nav item
    $(".nav .nav-link").click(function() {
      $(".nav .nav-link").each(function() {
        $(this).removeClass("active-nav-item");
      });
      $(this).addClass("active-nav-item"); 
      $(".nav .more").removeClass("active-nav-item");
    });
  });
</script>

app/views/refills/_searchbar.html.erb
  <div class="search-bar">
    <div class="search-and-submit">
      <input type="search" placeholder="Enter Search" />
      <button type="submit">
        <img src="https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon-black.png" alt="">
      </button>
    </div>
  </div>